services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - inception-net
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    build: ./wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: unless-stopped
    networks:
      - inception-net
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/www.conf:/usr/local/etc/php-fpm.d/www.conf


  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception-net
    volumes:
      - wordpress:/var/www/html
      - ./nginx/ssl/cert.pem:/etc/ssl/certs/cert.pem
      - ./nginx/ssl/key.pem:/etc/ssl/private/key.pem

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb



networks:
  inception-net: