services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - 3306
    restart: unless-stopped



  wordpress:
    build: ./wordpress
    container_name: wordpress
    expose:
      - 9000
    restart: unless-stopped



  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/caigner/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/caigner/data/mariadb



#networks:
