services:

  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306
    restart: unless-stopped
    networks:
      - docker-network
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    build: ./wordpress
    container_name: wordpress
    expose:
      - 9000
    restart: unless-stopped
    networks:
      - docker-network
    volumes:
      - ./wordpress/www.conf:/usr/local/etc/php-fpm.d/www.conf


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - docker-network
    volumes:
        - ./nginx/ssl/cert.pem:/etc/ssl/certs/cert.pem
        - ./nginx/ssl/key.pem:/etc/ssl/private/key.pem

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/caigner/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/caigner/data/mariadb



networks:
  docker-network:
    name: inception-net
    driver: bridge
