FROM debian:latest

# Install MariaDB
RUN	apt update && apt install -y \
	mariadb-server \
	&& rm -rf /var/lib/apt/lists/*

CMD	["mysqld_safe"]

#HEALTHCHECK	--interval=5s \
#		--timeout=5s \
#		--retries=3 \
#		CMD mysqladmin ping -h localhost
